### PR TITLE
Add *nix build instructions

### PR DESCRIPTION
**Pull request by anonyco**
I and many other people like easy instructions that I can copy-and-paste.

### CODE REVIEW

**Comment by myrsloik** [comment]
Exactly, this isn't a package manager tutorial. If you're that uncomfortable compiling things then binary packages are for you...

**Comment by anonyco** [comment]
> Exactly, this isn't a package manager tutorial. If you're that uncomfortable compiling things then binary packages are for you...

This. It's far easier to install from your distro's package manager if your distro's package manager has ffms2. Some distros (notably Debian and derivatives) don't have ffms2 in their repos, which necessitates compiling from source. Debian derivatives like Ubuntu and Linux Mint and PopOS flourish with Linux newbies who would much appreciate compilation instructions so they can install ffms2. In my opinion, we shouldn't force these people to retreat back to Windows just to use ffms2.

**Comment by myrsloik** [comment]
If you want to more or less provide build scripts you're free to do so. We simply don't want to be stuck with updating/maintaining them forever in the docs as they tent to break with every single major distro update. If you post it someplace maybe I'll even link it.

**Comment by anonyco** [comment]
Thank you for explaining that to me. I understand and will get this PR off your case.

**Pull request closed without merging**
