### PR TITLE
fixbug: audio maybe deap loop when DecodeNextBlock failed.

### PR DESCRIPTION
**Pull request by taniey**

### CODE REVIEW

**Comment by myrsloik** [comment]
Do you have a sample file where this happens?

**Comment by taniey** [comment]
Sorry, I have lost the audio file about this! But, I'm sure that it will dead loop .when DecodeNextBlock failed.
when I debug the audio decode(avcodec_receive_frame), I find the ffmpeg decode return 2048 bytes , and next decode (avcodec_receive_frame) return ( 0 bytes frame, the return value is AVERROR(EAGAIN)) (this condition very rarely , only once!) , so when decode return 0 ,the DecodeNextBlock  local valiable(NumberOfSamples) will return 0, and GetAudio function will can't return as the PacketNumber can't PacketNumber++.

**Comment by taniey** [comment]
> 
> 
> Do you have a sample file where this happens?

Sorry, I have lost the audio file about this! But, I'm sure that it will dead loop .when DecodeNextBlock failed.
when I debug the audio decode(avcodec_receive_frame), I find the ffmpeg decode return 2048 bytes , and next decode (avcodec_receive_frame) return ( 0 bytes frame, the return value is AVERROR(EAGAIN)) (this condition very rarely , only once!) , so when decode return 0 ,the DecodeNextBlock local valiable(NumberOfSamples) will return 0, and GetAudio function will can't return as the PacketNumber can't PacketNumber++.

**Comment by myrsloik** [comment]
No sample and a patch that mangles space so I can't be bothered to read it. Most likely caused by a mildly corrupt file as well.

**Pull request closed without merging**
