### PR TITLE
Remove HAALISOURCE stuff

### PR DESCRIPTION
**Pull request by qyot27**
Fix for #175 because I've also gotten sick of having to tell people to use `-m lavf` when indexing.

I also integrated it into the c_plugin branch, but I won't issue a pull request on that until after this gets into master.

### CODE REVIEW

**Comment by qyot27** [comment]
Regarding the Matroska demuxer this time. Should it be:
A) Removed with the HAALISOURCE demuxers
B) Made optional at configure time
C) Left completely alone

Personally, I'd say A, and I do have a basic patch that does this locally.  I'll push up a reorganized branch that covers removing both HAALISOURCE and the Matroska demuxer if that's what's settled on.

**Comment by tgoyne** [comment]
When I last looked into such things, VP8 in webm didn't work correctly with lavf. If that's no longer an issue then I don't think there's any reason to keep the matroska demuxer around. It's generally a little faster, but dropping support for multiple demuxers would probably cut ffms2 in half, including some of the uglier parts.

**Comment by qyot27** [comment]
I didn't have any WebM files (VP8 or VP9) to test against, so I went looking for samples and found these:

www.ioncannon.net/examples/vp8-webm/demo.html

http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5

https://archive.org/details/WebmVp8Vorbis

At least for these samples, the frames match when seeking back and forth in the script in VDub, timecodes in FFInfo and VDub match, and I didn't notice anything weird about the decoding quality.

I'd also dove into FFmpeg's commit log to see if I could find anything explicitly about VP8-in-WebM over the past year or so, but I couldn't.  But the large number of general Matroska fixes is probably shadowing that.

I think I'll go ahead and push it up to the branch for review anyway.  I was a bit cautious about places where there was branching for multiple demuxers and simply removed the the Matroska branch, since I wasn't sure if the proper way to handle that would be to mark the relevant parts of the API as deprecated first (which would probably be better as a separate commit), and wait for that before refactoring the places where it had been used.

Let's just hope Github doesn't close this pull request because I'll have to use --force.

**Comment by qyot27** [comment]
Ping?

**Comment by myrsloik** [comment]
I double ping. I may want to make some minor changes but don't want to start until this stuff has been cleared out.

**Comment by tophf** [comment]
FWIW, regarding webm with VP8/VP9, it'd be probably reasonable to test the most widely used source of such files - youtube. Those videos are easy to find by searching for e.g. "4K" if youtube/html5 player with mediasource extensions support is enabled in browser. The question remains, though, whether to mux the separate video/audio tracks and which tool (ffmpeg?) is most popular.

**Comment by dwbuiten** [comment]
> The question remains, though, whether to mux the separate video/audio tracks and which tool (ffmpeg?) is most popular.

ffmpeg, mkvtoolnix, and webmtools. Try all three?

**Comment by myrsloik** [comment]
Make it two steps:
1. Remove directshowshit nobody ever uses
2. Ponder the default mkv parser
I'd be very happy if 1 is done quickly

**Comment by qyot27** [comment]
I posted a LAVF-only build on the 15th.  There's currently been 104 downloads, and no-one has complained about WebM or offered any confirmation of it working/not working.  I don't know if that should be considered a 'no news is good news' situation or not (it could be that it works fine so no reason to comment, or the ones downloading the builds just don't grab many WebM files).

**Comment by qyot27** [comment]
It's been a month now since I posted the build (now with 234 downloads), and haven't received any complaints about either the DirectShow removal or the removal of the Matroska demuxer.

**Comment by tgoyne** [comment]
I finally got around to testing this and lavf seemed fine on all the stuff I had lying around that at some point worked with the matroska/haali sources but not lavf, so I merged it with some more changes.

**Pull request closed without merging**
